package threadrelay;

import javax.swing.SwingUtilities;

/**
 * Form principale della staffetta.
 * Implementa Observer per ricevere le notifiche di posizione e fine corsa
 * direttamente dai Runner, seguendo il pattern Observer/Subject.
 *
 * La catena staffetta funziona come nell'implementazione originale:
 * ogni Runner sa chi è il suo successore tramite setProssimoRunner()
 * e lo avvia da solo a posizione 90.
 */
public class Gara extends javax.swing.JFrame implements Observer {

    private javax.swing.JLabel[] iconeRunners;
    private javax.swing.JLabel[] testiPunteggi;
    private Runner[] runnersAttivi = new Runner[4];

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Gara.class.getName());

    /**
     * Creates new form Gara
     */
    public Gara() {
        initComponents();
        iconeRunners = new javax.swing.JLabel[]{
            lbl_Corridore1, lbl_Corridore2, lbl_Corridore3, lbl_Corridore4
        };
        testiPunteggi = new javax.swing.JLabel[]{
            lbl_pRunner1, lbl_pRunner2, lbl_pRunner3, lbl_pRunner4
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Corsie = new javax.swing.JPanel();
        pnl_Corsia1 = new javax.swing.JPanel();
        lbl_Corridore1 = new javax.swing.JLabel();
        pnl_Corsia2 = new javax.swing.JPanel();
        lbl_Corridore2 = new javax.swing.JLabel();
        pnl_Corsia3 = new javax.swing.JPanel();
        lbl_Corridore3 = new javax.swing.JLabel();
        pnl_Corsia4 = new javax.swing.JPanel();
        lbl_Corridore4 = new javax.swing.JLabel();
        pnl_Controlli = new javax.swing.JPanel();
        cbx_Velocita = new javax.swing.JComboBox<>();
        btn_Avvia = new javax.swing.JButton();
        btn_Sospende = new javax.swing.JButton();
        btn_Riprende = new javax.swing.JButton();
        btn_Ferma = new javax.swing.JButton();
        pnl_Info = new javax.swing.JPanel();
        pnl_nRunner1 = new javax.swing.JPanel();
        lbl_nRunner1 = new javax.swing.JLabel();
        lbl_pRunner1 = new javax.swing.JLabel();
        pnl_nRunner2 = new javax.swing.JPanel();
        lbl_nRunner2 = new javax.swing.JLabel();
        lbl_pRunner2 = new javax.swing.JLabel();
        pnl_nRunner3 = new javax.swing.JPanel();
        lbl_nRunner3 = new javax.swing.JLabel();
        lbl_pRunner3 = new javax.swing.JLabel();
        pnl_nRunner4 = new javax.swing.JPanel();
        lbl_nRunner4 = new javax.swing.JLabel();
        lbl_pRunner4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 350));
        setPreferredSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        pnl_Corsie.setAutoscrolls(true);
        pnl_Corsie.setLayout(new java.awt.GridLayout(4, 0, 1, 5));

        pnl_Corsia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_Corsia1.setLayout(null);
        lbl_Corridore1.setText("🏃");
        lbl_Corridore1.setToolTipText("");
        pnl_Corsia1.add(lbl_Corridore1);
        lbl_Corridore1.setBounds(10, 30, 20, 20);
        lbl_Corridore1.getAccessibleContext().setAccessibleName("");
        pnl_Corsie.add(pnl_Corsia1);

        pnl_Corsia2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_Corsia2.setLayout(null);
        lbl_Corridore2.setText("🏃");
        lbl_Corridore2.setToolTipText("");
        pnl_Corsia2.add(lbl_Corridore2);
        lbl_Corridore2.setBounds(10, 30, 20, 20);
        pnl_Corsie.add(pnl_Corsia2);

        pnl_Corsia3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_Corsia3.setLayout(null);
        lbl_Corridore3.setText("🏃");
        lbl_Corridore3.setToolTipText("");
        pnl_Corsia3.add(lbl_Corridore3);
        lbl_Corridore3.setBounds(10, 30, 20, 20);
        pnl_Corsie.add(pnl_Corsia3);

        pnl_Corsia4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_Corsia4.setLayout(null);
        lbl_Corridore4.setText("🏃");
        lbl_Corridore4.setToolTipText("");
        pnl_Corsia4.add(lbl_Corridore4);
        lbl_Corridore4.setBounds(10, 30, 20, 20);
        pnl_Corsie.add(pnl_Corsia4);

        getContentPane().add(pnl_Corsie, java.awt.BorderLayout.CENTER);

        pnl_Controlli.setPreferredSize(new java.awt.Dimension(800, 80));

        cbx_Velocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Slow", "Regular", "Fast"}));
        cbx_Velocita.setSelectedIndex(1);
        pnl_Controlli.add(cbx_Velocita);

        btn_Avvia.setText("Avvia");
        btn_Avvia.addActionListener(this::btn_AvviaActionPerformed);
        pnl_Controlli.add(btn_Avvia);

        btn_Sospende.setText("Sospende");
        btn_Sospende.setEnabled(false);
        btn_Sospende.addActionListener(this::btn_SospendeActionPerformed);
        pnl_Controlli.add(btn_Sospende);

        btn_Riprende.setText("Riprende");
        btn_Riprende.setEnabled(false);
        btn_Riprende.addActionListener(this::btn_RiprendeActionPerformed);
        pnl_Controlli.add(btn_Riprende);

        btn_Ferma.setText("Ferma");
        btn_Ferma.setEnabled(false);
        btn_Ferma.addActionListener(this::btn_FermaActionPerformed);
        pnl_Controlli.add(btn_Ferma);

        getContentPane().add(pnl_Controlli, java.awt.BorderLayout.SOUTH);

        pnl_Info.setPreferredSize(new java.awt.Dimension(180, 0));
        pnl_Info.setLayout(new java.awt.GridLayout(4, 0, 1, 5));

        pnl_nRunner1.setBackground(new java.awt.Color(215, 230, 245));
        pnl_nRunner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_nRunner1.setLayout(new java.awt.BorderLayout());
        lbl_nRunner1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbl_nRunner1.setText("Runner 1");
        pnl_nRunner1.add(lbl_nRunner1, java.awt.BorderLayout.CENTER);
        lbl_pRunner1.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lbl_pRunner1.setText("    0    ");
        pnl_nRunner1.add(lbl_pRunner1, java.awt.BorderLayout.LINE_END);
        pnl_Info.add(pnl_nRunner1);

        pnl_nRunner2.setBackground(new java.awt.Color(215, 230, 245));
        pnl_nRunner2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_nRunner2.setLayout(new java.awt.BorderLayout());
        lbl_nRunner2.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbl_nRunner2.setText("Runner 2");
        pnl_nRunner2.add(lbl_nRunner2, java.awt.BorderLayout.CENTER);
        lbl_pRunner2.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lbl_pRunner2.setText("    0    ");
        pnl_nRunner2.add(lbl_pRunner2, java.awt.BorderLayout.LINE_END);
        pnl_Info.add(pnl_nRunner2);

        pnl_nRunner3.setBackground(new java.awt.Color(215, 230, 245));
        pnl_nRunner3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_nRunner3.setLayout(new java.awt.BorderLayout());
        lbl_nRunner3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbl_nRunner3.setText("Runner 3");
        pnl_nRunner3.add(lbl_nRunner3, java.awt.BorderLayout.CENTER);
        lbl_pRunner3.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lbl_pRunner3.setText("    0    ");
        pnl_nRunner3.add(lbl_pRunner3, java.awt.BorderLayout.LINE_END);
        pnl_Info.add(pnl_nRunner3);

        pnl_nRunner4.setBackground(new java.awt.Color(215, 230, 245));
        pnl_nRunner4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnl_nRunner4.setLayout(new java.awt.BorderLayout());
        lbl_nRunner4.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbl_nRunner4.setText("Runner 4");
        pnl_nRunner4.add(lbl_nRunner4, java.awt.BorderLayout.CENTER);
        lbl_pRunner4.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lbl_pRunner4.setText("    0    ");
        pnl_nRunner4.add(lbl_pRunner4, java.awt.BorderLayout.LINE_END);
        pnl_Info.add(pnl_nRunner4);

        getContentPane().add(pnl_Info, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ------------------------------------------------------------------ Azioni bottoni

    private void btn_AvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AvviaActionPerformed
        int v = switch (cbx_Velocita.getSelectedIndex()) {
            case 0 -> 100;
            case 2 -> 10;
            default -> 50;
        };

        // Crea i 4 runner registrando il form come Observer
        for (int i = 0; i < 4; i++) {
            runnersAttivi[i] = new Runner(i + 1, v);
            runnersAttivi[i].addObserver(this);
        }

        // Collega la catena staffetta come nell'implementazione originale
        runnersAttivi[0].setProssimoRunner(runnersAttivi[1]);
        runnersAttivi[1].setProssimoRunner(runnersAttivi[2]);
        runnersAttivi[2].setProssimoRunner(runnersAttivi[3]);
        runnersAttivi[3].setProssimoRunner(null);

        // Riporta le icone alla posizione di partenza
        for (javax.swing.JLabel icona : iconeRunners) {
            icona.setLocation(10, icona.getY());
        }
        for (javax.swing.JLabel testo : testiPunteggi) {
            testo.setText("    0    ");
        }

        btn_Avvia.setEnabled(false);
        cbx_Velocita.setEnabled(false);
        btn_Sospende.setEnabled(true);
        btn_Ferma.setEnabled(true);
        btn_Riprende.setEnabled(false);

        // Parte solo il primo; sarà lui ad avviare il secondo a pos. 90, e così via
        new Thread(runnersAttivi[0]).start();
    }//GEN-LAST:event_btn_AvviaActionPerformed

    private void btn_SospendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SospendeActionPerformed
        for (Runner r : runnersAttivi) {
            if (r != null) r.sospendi();
        }
        btn_Riprende.setEnabled(true);
        btn_Sospende.setEnabled(false);
    }//GEN-LAST:event_btn_SospendeActionPerformed

    private void btn_RiprendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RiprendeActionPerformed
        for (Runner r : runnersAttivi) {
            if (r != null) r.riprendi();
        }
        btn_Riprende.setEnabled(false);
        btn_Sospende.setEnabled(true);
    }//GEN-LAST:event_btn_RiprendeActionPerformed

    private void btn_FermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FermaActionPerformed
        for (Runner r : runnersAttivi) {
            if (r != null) r.ferma();
        }
        btn_Avvia.setEnabled(true);
        cbx_Velocita.setEnabled(true);
        btn_Sospende.setEnabled(false);
        btn_Riprende.setEnabled(false);
        btn_Ferma.setEnabled(false);
    }//GEN-LAST:event_btn_FermaActionPerformed

    // ------------------------------------------------------------------ Observer

    /**
     * Riceve la posizione aggiornata dal Runner (pattern Observer).
     * Sostituisce aggiornaPosizione() del vecchio RunnerListener.
     */
    @Override
    public void update(int idRunner, int posizione) {
        SwingUtilities.invokeLater(() -> {
            int indice = idRunner - 1;

            testiPunteggi[indice].setText("    " + posizione + "    ");

            javax.swing.JLabel icona = iconeRunners[indice];
            int larghezzaCorsia    = icona.getParent().getWidth();
            int spazioPercorribile = larghezzaCorsia - icona.getWidth();
            int nuovaX = (posizione * spazioPercorribile) / 99;
            icona.setLocation(nuovaX, icona.getY());
        });
    }

    /**
     * Riceve la notifica di fine corsa dal Runner (pattern Observer).
     * Sostituisce corsaFinita() del vecchio RunnerListener.
     */
    @Override
    public void corsaFinita(int idRunner) {
        SwingUtilities.invokeLater(() -> {
            testiPunteggi[idRunner - 1].setText("  Fine  ");
            if (idRunner == 4) {
                btn_Avvia.setEnabled(true);
                cbx_Velocita.setEnabled(true);
                btn_Sospende.setEnabled(false);
                btn_Ferma.setEnabled(false);
                btn_Riprende.setEnabled(false);
            }
        });
    }

    // ------------------------------------------------------------------ Main

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Gara().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Avvia;
    private javax.swing.JButton btn_Ferma;
    private javax.swing.JButton btn_Riprende;
    private javax.swing.JButton btn_Sospende;
    private javax.swing.JComboBox<String> cbx_Velocita;
    private javax.swing.JLabel lbl_Corridore1;
    private javax.swing.JLabel lbl_Corridore2;
    private javax.swing.JLabel lbl_Corridore3;
    private javax.swing.JLabel lbl_Corridore4;
    private javax.swing.JLabel lbl_nRunner1;
    private javax.swing.JLabel lbl_nRunner2;
    private javax.swing.JLabel lbl_nRunner3;
    private javax.swing.JLabel lbl_nRunner4;
    private javax.swing.JLabel lbl_pRunner1;
    private javax.swing.JLabel lbl_pRunner2;
    private javax.swing.JLabel lbl_pRunner3;
    private javax.swing.JLabel lbl_pRunner4;
    private javax.swing.JPanel pnl_Controlli;
    private javax.swing.JPanel pnl_Corsia1;
    private javax.swing.JPanel pnl_Corsia2;
    private javax.swing.JPanel pnl_Corsia3;
    private javax.swing.JPanel pnl_Corsia4;
    private javax.swing.JPanel pnl_Corsie;
    private javax.swing.JPanel pnl_Info;
    private javax.swing.JPanel pnl_nRunner1;
    private javax.swing.JPanel pnl_nRunner2;
    private javax.swing.JPanel pnl_nRunner3;
    private javax.swing.JPanel pnl_nRunner4;
    // End of variables declaration//GEN-END:variables
}
